version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mymysql
    hostname: mymysql
    restart: always
    environment:
      - MYSQL_DATABASE=todo_list
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db