version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=todo_list
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3302:3306"

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db