# Generated by Django 4.1.2 on 2023-02-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.TextField(default='default'),
        ),
    ]
